src/Entity/Degree.php
<?php

namespace App\Entity;

use App\Entity\Candidate;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DegreeRepository")
 */
class Degree
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $acronym;
 
    /**
     * @ORM\Column(type="string", length=5)
     */
    private $degree_level;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Candidate", mappedBy="degree", cascade={"persist", "remove"})
     * 
     */
    private $candidate;

    public function __toString(): string
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAcronym(): ?string
    {
        return $this->acronym;
    }

    public function setAcronym(string $acronym): self
    {
        $this->acronym = $acronym;

        return $this;
    }

    public function getDegreeLevel(): ?string
    {
        return $this->degree_level;
    }

    public function setDegreeLevel(string $degree_level): self
    {
        $this->degree_level = $degree_level;

        return $this;
    }

    public function getCandidate(): ?Candidate
    {
        return $this->candidate;
    }

    public function setCandidate(?Candidate $candidate): self
    {
        $this->candidate = $candidate;

        // set (or unset) the owning side of the relation if necessary
        $newDegree = null === $candidate ? null : $this;
        if ($candidate->getDegree() !== $newDegree) {
            $candidate->setDegree($newDegree);
        }

        return $this;
    }



}

src/Form/DegreeType.php
<?php

namespace App\Form;

use App\Entity\Candidate;
use App\Entity\Degree;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints;

class DegreeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    { 
        $builder
            ->add('name',TextType::class, [
                'label' => 'name'
            ])
            ->add('acronym',TextType::class, [
                    'constraints' => [
                        new Constraints\Length([
                            'min' => 3,
                            'max' => 10,
                            'exactMessage' => 'The acronym must contain {{ limit }} character'
                        ])
                        
                    ],
                'label' => 'Acronym'

            ])
            ->add('degree_level',TextType::class, [
                'constraints' => [
                    new Constraints\Length([
                        'min' => 1,
                        'max' => 8,
                        'exactMessage' => 'The Degree level must contain {{ limit }} character (I,II,III,IV,V, VI, VII, VIII)'
                    ])
                    
                ],
                'label' => 'Degree level'
            ]) 
            ->add('candidate')
  
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Degree::class,
        ]);
    } 
}

src/Controller/DegreeController.php
<?php

namespace App\Controller;

use App\Entity\Degree;
use App\Form\DegreeType;
use App\Repository\DegreeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/degree")
 */
class DegreeController extends AbstractController
{
    /** 
     * @Route("/", name="degree_index", methods={"GET"})
     */
    public function index(DegreeRepository $degreeRepository): Response
    {
        return $this->render('degree/index.html.twig', [
            'degrees' => $degreeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="degree_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $degree = new Degree();
        $form = $this->createForm(DegreeType::class, $degree);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($degree);
            $entityManager->flush();

            return $this->redirectToRoute('degree_index');
        }

        return $this->render('degree/new.html.twig', [
            'degree' => $degree,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="degree_show", methods={"GET"})
     */
    public function show(Degree $degree): Response
    {
        return $this->render('degree/show.html.twig', [
            'degree' => $degree,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="degree_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Degree $degree): Response
    {
        $form = $this->createForm(DegreeType::class, $degree);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('degree_index');
        }

        return $this->render('degree/edit.html.twig', [
            'degree' => $degree,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="degree_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Degree $degree): Response
    {
        if ($this->isCsrfTokenValid('delete'.$degree->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($degree);
            $entityManager->flush();
        }

        return $this->redirectToRoute('degree_index');
    }
}

templates/degree/_delete_form.html.twig
<form method="post" action="{{ path('degree_delete', {'id': degree.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ degree.id) }}">
    <button class="btn">Delete</button>
</form>

templates/degree/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/degree/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Degree{% endblock %}

{% block body %}
    <h1>Edit Degree</h1>

    {{ include('degree/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('degree_index') }}"class="btn btn-dark m-3">back to list</a>

    {{ include('degree/_delete_form.html.twig') }}
{% endblock %}

templates/degree/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Degree index{% endblock %}

{% block body %}
    <h1>Degree index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Acronym</th>
                <th>Degree level</th>
                <th>Candidate</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for degree in degrees %}
            <tr>
                <td>{{ degree.id }}</td>
                <td>{{ degree.name }}</td>
                <td>{{ degree.acronym }}</td>
                <td>{{ degree.degreeLevel }}</td>
                <td>{{ degree.candidate }}</td>
                <td>
                    <a href="{{ path('degree_show', {'id': degree.id}) }}">show</a>
                    <a href="{{ path('degree_edit', {'id': degree.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('degree_new') }}" class="btn btn-dark m-3">Create new</a>
{% endblock %}

templates/degree/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Degree{% endblock %}

{% block body %}
    <h1>Create new Degree</h1>

    {{ include('degree/_form.html.twig') }}
    <a href="{{ path('degree_index') }}" class="btn btn-dark m-3">back to list</a>
{% endblock %}

templates/degree/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Degree{% endblock %}

{% block body %}
    <h1>Degree</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ degree.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ degree.name }}</td>
            </tr>
            <tr>
                <th>Acronym</th>
                <td>{{ degree.acronym }}</td>
            </tr>
            <tr>
                <th>Degree_level</th>
                <td>{{ degree.degreeLevel }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('degree_index') }}" class="btn btn-dark m-3">back to list</a>

    <a href="{{ path('degree_edit', {'id': degree.id}) }}" class="btn btn-dark m-3">edit</a>

    {{ include('degree/_delete_form.html.twig') }}
{% endblock %}