src/Entity/Company.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CompanyRepository")
 */
class Company
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue() 
     * @ORM\Column(type="integer")
     */
    private $id;    

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $domain;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nationality;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $creation_date;
     /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;

    /**
     * @ORM\Column(type="string")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city; 

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="company")
     * @ORM\JoinColumn(nullable=false)
     * 
     */
    private $user;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDomain(): ?string
    {
        return $this->domain;
    }

    public function setDomain(string $domain): self
    {
        $this->domain = $domain;

        return $this;
    }
    
    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(?string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(?\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }
    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }
    public function setUser(?User $user): self
    {
        $this->user = $user;
        return $this;
    }
}

src/Form/CompanyType.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',TextType::class, [
                'label' => 'Name of the company'
            ])
            ->add('domain',TextType::class, [
                'label' => 'Domain'
            ])
            ->add('nationality',TextType::class, [
                'label' => 'Nationality' 
            ])
            ->add('creation_date',DateType::class, [
                'widget' => 'single_text', 
                'required' => false
            ])
            ->add('street', TextType::class,[
                'label' => 'Street'
            ])
            ->add('zip_code',NumberType::class,[
                'constraints' => [
                    new Constraints\Length([
                    'min' => 5,
                    'max' => 5,
                    'exactMessage' => 'The zip code must composed of 5 figure'
                ]),
                    new Constraints\Regex([
                    "pattern" => '/[0-9]{5}/',
                    "message" => 'The zip code must composed of 5 figure from 0 to 9'
                ])
            ],
            ])
            ->add('city',TextType::class, [
                'label' => 'City'
            ])
            ->add('country',TextType::class, [
                'label' => 'Country'
            ])
            ->add('user',EntityType::class, [
                'class' => User::class,
                'choice_label' => 'username',
                'multiple' => true,
                'expanded' => true,
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
        ]);
    }
}

src/Controller/CompanyController.php
<?php

namespace App\Controller;

use App\Entity\Company;
use App\Entity\User;
use App\Form\CompanyType;
use App\Repository\CompanyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class CompanyController extends AbstractController
{
    /**
     * @Route("/user/company", name="company_index", methods={"GET"})
     */
    public function index(CompanyRepository $companyRepository): Response
    {
        return $this->render('company/index.html.twig', [
            'companies' => $companyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/user/company/new", name="company_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $company = new Company();
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($company);
            $entityManager->flush();

            return $this->redirectToRoute('company_index');
        }

        return $this->render('company/new.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/user/company/{id}/show", name="company_show", methods={"GET"}, requirements={"id"="\d+"})
     */
    public function show(Company $company): Response
    {
        return $this->render('company/show.html.twig', [
            'company' => $company,
        ]);
    }

    /**
     * @Route("/user/company/{id}/edit", name="company_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Company $company): Response
    {
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('company_index');
        }
        
        return $this->render('company/edit.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("/user/company/{id}/delete", name="company_delete", methods={"DELETE"}, requirements={"id"="\d+"}))
     */
    public function delete(Request $request, Company $company): Response
    {
        if ($this->isCsrfTokenValid('delete'.$company->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($company);
            $entityManager->flush();
        }

        return $this->redirectToRoute('company_index');
    }
}

templates/company/_delete_form.html.twig
<form method="post" action="{{ path('company_delete', {'id': company.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ company.id) }}">
    <button class="btn">Delete</button>
</form>

templates/company/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-dark m-3">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/company/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Company{% endblock %}

{% block body %}
    <h1>Edit Company</h1>

    {{ include('company/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('company_index') }}" class="btn btn-dark m-3">back to list</a>

    {{ include('company/_delete_form.html.twig') }}
{% endblock %}

templates/company/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Company index{% endblock %}

{% block body %}
    <h1>Company index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Domain</th> 
                <th>Nationality</th>
                <th>Creation date</th>
                <th>Street</th>
                <th>Zip Code</th>
                <th>City</th>
                <th>Country</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for company in companies %}
            <tr>
                <td>{{ company.id }}</td>
                <td>{{ company.name }}</td>
                <td>{{ company.domain }}</td>
                <td>{{ company.nationality }}</td>
                <td>{{ company.creationDate ? company.creationDate|date('Y-m-d') : '' }}</td>
                <td>{{ company.street }}</td>
                <td>{{ company.zipCode }}</td>
                <td>{{ company.city }}</td>
                <td>{{ company.country }}</td>
                <td>
                    <a href="{{ path('company_show', {'id': company.id}) }}">show</a>
                    <a href="{{ path('company_edit', {'id': company.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('company_new') }}" class="btn btn-dark m-3">Create new</a>
{% endblock %}

templates/company/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Company{% endblock %}

{% block body %}
    <h1>Create new Company</h1>

    {{ include('company/_form.html.twig') }}

    <a href="{{ path('company_index') }}" class="btn btn-dark m-3">back to list</a>
{% endblock %}

templates/company/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Company{% endblock %}

{% block body %}
    <h1>Company</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ company.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ company.name }}</td>
            </tr>
            <tr>
                <th>Domain</th>
                <td>{{ company.domain }}</td>
            </tr>
            <tr>
                <th>Nationality</th>
                <td>{{ company.nationality }}</td>
            </tr>
            <tr>
                <th>Creation_date</th>
                <td>{{ company.creationDate ? company.creationDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('company_index') }}" class="btn btn-dark m-3">back to list</a>

    <a href='{{ path("company_edit", {"id": company.id}) }}' class="btn btn-dark m-3">edit</a>

    {{ include('company/_delete_form.html.twig') }}
{% endblock %}